export const ADD_LFORM = "ADD_LFORM";
export const DELETE_LFORM = "DELETE_LFORM";
export const EDIT_LFORM = "EDIT_LFORM";
export const SET_LEADERS_LIST = "SET_LEADERS_LIST";
export const NEW_CURRENT_DAY = "NEW_CURRENT_DAY";
export const PREV_CURRENT_DAY = "PREV_CURRENT_DAY";
export const NEXT_CURRENT_DAY = "NEXT_CURRENT_DAY";
